apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-api
  description: My .NET API
  annotations:
    backstage.io/github-repository: https://github.com/NimmyDBS/MyApi
    backstage.io/has-api-docs: true
    backstage.io/has-mock-data: false
    backstage.io/owner: guests
spec:
  type: service
  lifecycle: production
  owner: guests
  implementsApis:
    - owner: guests
      provideApis:
        - kind: openapi
          lifecycle: production
          value: /openapi/hello.yaml
