apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MyApi
  annotations:
    github.com/project-slug: NimmyDBS/MyApi
spec:
  type: service
  lifecycle: experimental
  owner: guests
  providesApis:
    - name: hello
      openApiDefinitionPath: /openapi/hello.yaml
    - name: greet
      openApiDefinitionPath: /openapi/greet.yaml
